### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by gertvdv** [chenzhihao/easy-promise-queue#16]
When downloading this package through npm, it seems to only download some of the files.

**Comment by cmcleese** [comment]
Indeed there is a issue install `v0.5.5` via npm.

rollback to `v0.5.4` until the issue is resolved.

**Comment by chenzhihao** [comment]
Sorry! I made a stupid mistake before...
I published it before I built it.

Fix: https://github.com/chenzhihao/easy-promise-queue/pull/17

Published as `v0.5.6`. Please re-install it, thanks.

**Comment by cmcleese** [comment]
> Sorry! I made a stupid mistake before...
> I published it before I built it.
> 
> Fix: #17
> 
> Published as `v0.5.6`. Please re-install it, thanks.

That was fast. Thanks!
Working
